import axios from "axios";
import Head from 'next/head'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {

  const [cpf, setCpf] = useState('');

  function handleSubmit() {
    const options = {
      method: 'POST',
      url: 'http://localhost:3333/usuario/login',
      headers: { 'Content-Type': 'application/json' },
      data: { cpf }
    };

    axios.request(options).then(function (response) {
      console.log(response.data);
    }).catch(function (error) {
      console.error(error);
    });
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Onl Sistema - Login</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={styles.titulo}>
        <h1>Login Page</h1>
      </div>
      <form onSubmit={handleSubmit()}>
        <div className={styles.login}>
          <div className={styles.grupoInput}>
            <label>CPF: </label>
            <input type="text" value={cpf} onChange={(e) => { setCpf(e.target.value) }} class="cpf" maxlength="11" pattern="(\d{3}\.?\d{3}\.?\d{3}-?\d{2})" require />
          </div>
          <button type="submit" className='btn btnSucesso'>
            Logar
          </button>
        </div>
      </form>
    </div>
  )
}
